server:
  port: "8868"
  mode: "debug"  # debug, release

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "blog"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 7

minio:
  endpoint: "localhost:9000"
  access_key_id: "admin"
  secret_access_key: "admin123"
  use_ssl: false
  bucket_name: "blog-files"

jwt:
  secret: "qwertyuiopasdfghjklzxcvbnm,u6ytgjh"
  expire_hour: 24
